language: __connie__
sudo: required
dist: trusty
group: stable
script:
- curl -sSLO https://raw.githubusercontent.com/travis-ci/packer-templates/master/packer-scripts/dump-dpkg-manifest
- chmod +x dump-dpkg-manifest
- sudo ./dump-dpkg-manifest | tee dpkg-manifest.json
matrix:
  include:
  - language: __garnet__
  - language: __amethyst__
  - language: __sugilite__
