language: ruby
# sudo: false
# env:
# - MATRIX_EXPLOSION=1
# - MATRIX_EXPLOSION=2
# - MATRIX_EXPLOSION=3
# - MATRIX_EXPLOSION=4
# - MATRIX_EXPLOSION=5
# - MATRIX_EXPLOSION=6
# - MATRIX_EXPLOSION=7
# - MATRIX_EXPLOSION=8
# - MATRIX_EXPLOSION=9
# - MATRIX_EXPLOSION=10
# - MATRIX_EXPLOSION=11
# - MATRIX_EXPLOSION=12
# - MATRIX_EXPLOSION=13
# - MATRIX_EXPLOSION=14
# - MATRIX_EXPLOSION=15
# - MATRIX_EXPLOSION=16
# - MATRIX_EXPLOSION=17
# - MATRIX_EXPLOSION=18
# - MATRIX_EXPLOSION=19
# - MATRIX_EXPLOSION=20
# - MATRIX_EXPLOSION=21
# - MATRIX_EXPLOSION=22
# - MATRIX_EXPLOSION=23
# - MATRIX_EXPLOSION=24
# - MATRIX_EXPLOSION=25
# - MATRIX_EXPLOSION=26
# - MATRIX_EXPLOSION=27
# - MATRIX_EXPLOSION=28
# - MATRIX_EXPLOSION=29
# - MATRIX_EXPLOSION=30
rvm: 2.1.3
# before_script:
# - curl -sL "http://www.coker.com.au/bonnie++/bonnie++-1.03e.tgz" | tar xzf -
# - cd bonnie++-1.03e && ./configure --prefix=$HOME && make && make install
# script:
# - bundle exec rspec
# - ~/sbin/bonnie++ -s 1024:256 -r 512
script: strace bundle exec rake spec --trace > rake-spec-trace.txt 2>&1
addons:
  artifacts:
    permissions: public-read
    key: AKIAIC7VUBYOOQIBU53Q
    secret:
      secure: G9jkpW8J3GgccSzDEjYKJRlYi3jVF6DIWWDRkL7K1FqG95MVTre0wbR+fVPLaz7l4uwIRrdjl8CY8Eqzhb2W03VB/nBI7+Jss44pMj7f5EXOlS5y2JMy+eWY2BlGYCvrDc4m6zMidQBnPEWocxsGOnZ+G8X3UmvXIaNXzliS1RU=
    bucket: tmp-28e6bfbb755300bbe36199b77ca5423560de5a69de69a8ff2bb7e6b1c169dd2c
