language: ruby
sudo: false
env:
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=1
rvm:
- 1.9.3
- 2.1.3
- jruby-19mode
- rbx
bundler_args: --jobs=1
script: bundle exec rspec
