language: ruby
sudo: false
env:
- MATRIX_EXPLOSION=1
- MATRIX_EXPLOSION=2
- MATRIX_EXPLOSION=3
- MATRIX_EXPLOSION=4
- MATRIX_EXPLOSION=5
- MATRIX_EXPLOSION=6
- MATRIX_EXPLOSION=7
- MATRIX_EXPLOSION=8
- MATRIX_EXPLOSION=9
- MATRIX_EXPLOSION=10
- MATRIX_EXPLOSION=11
- MATRIX_EXPLOSION=12
- MATRIX_EXPLOSION=13
- MATRIX_EXPLOSION=14
- MATRIX_EXPLOSION=15
- MATRIX_EXPLOSION=16
- MATRIX_EXPLOSION=17
- MATRIX_EXPLOSION=18
- MATRIX_EXPLOSION=19
- MATRIX_EXPLOSION=20
- MATRIX_EXPLOSION=21
- MATRIX_EXPLOSION=22
- MATRIX_EXPLOSION=23
- MATRIX_EXPLOSION=24
- MATRIX_EXPLOSION=25
- MATRIX_EXPLOSION=26
- MATRIX_EXPLOSION=27
- MATRIX_EXPLOSION=28
- MATRIX_EXPLOSION=29
- MATRIX_EXPLOSION=30
rvm:
- 1.9.3
- 2.1.3
- jruby-19mode
- rbx
bundler_args: --jobs=1
script: bundle exec rspec
